// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using parcial1;

namespace parcial1.Migrations
{
    [DbContext(typeof(tareasDbContext))]
    [Migration("20201007211918_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("parcial1.Detalles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Recursoiduser")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Tareaidtarea")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tiempo")
                        .HasColumnType("TEXT");

                    b.Property<int>("idrecurso")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idtarea")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("Recursoiduser");

                    b.HasIndex("Tareaidtarea");

                    b.ToTable("detalles");
                });

            modelBuilder.Entity("parcial1.Recursos", b =>
                {
                    b.Property<int>("iduser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioPK")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idusuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("iduser");

                    b.HasIndex("UsuarioPK");

                    b.ToTable("recursos");
                });

            modelBuilder.Entity("parcial1.Usuarios", b =>
                {
                    b.Property<int>("UsuarioPK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnName("Password")
                        .HasColumnType("char(20");

                    b.Property<string>("User")
                        .HasColumnType("TEXT")
                        .HasMaxLength(15);

                    b.HasKey("UsuarioPK");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("parcial1.tareas", b =>
                {
                    b.Property<int>("idtarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estimacion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Responsableiduser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Vencimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("idrecurso")
                        .HasColumnType("INTEGER");

                    b.HasKey("idtarea");

                    b.HasIndex("Responsableiduser");

                    b.ToTable("tareas");
                });

            modelBuilder.Entity("parcial1.Detalles", b =>
                {
                    b.HasOne("parcial1.Recursos", "Recurso")
                        .WithMany()
                        .HasForeignKey("Recursoiduser");

                    b.HasOne("parcial1.tareas", "Tarea")
                        .WithMany()
                        .HasForeignKey("Tareaidtarea");
                });

            modelBuilder.Entity("parcial1.Recursos", b =>
                {
                    b.HasOne("parcial1.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioPK");
                });

            modelBuilder.Entity("parcial1.tareas", b =>
                {
                    b.HasOne("parcial1.Recursos", "Responsable")
                        .WithMany()
                        .HasForeignKey("Responsableiduser");
                });
#pragma warning restore 612, 618
        }
    }
}
